<a href="https://colab.research.google.com/github/Narware-Ayush/AI_ML/blob/main/DataLoader.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# minibach gradient decent
batch_size=32
epochs=25
n_sample=len(xtrain_tensor)

for epoch in renge(epochs):
  for start_idx in range(0,n_sample,batch_size):
    end_idx=start_idx+batch_size
    x_batch=xtrain_tensor[start_idx:end_idx]
    y_batch=ytrain_tensor[start_idx:end_idx]

    #forward pass
    ypred=model(x_batch)
    loss=loss_function(ypred,y_batch.view(-1,1))

    #update step
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

print(f"epoch : {epoch+1} Loss : {loss.item()}")


NameError: name 'xtrain_tensor' is not defined

In [3]:
from sklearn.datasets import make_classification
import torch



In [4]:
from numpy.random.mtrand import rand
x,y=make_classification(n_samples=10,n_features=2,n_informative=2,n_redundant=0,n_classes=2,random_state=42)

In [6]:
y

array([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [7]:

x=torch.tensor(x,dtype=torch.float32)
y=torch.tensor(y,dtype=torch.long)

In [9]:
from torch.utils.data import Dataset, DataLoader


In [10]:
class CustomDataSet(Dataset):
  def __init__(self,features,labels):
    self.features=features
    self.labels=labels

  def __len__(self):
    return self.features.shape[0]

  def __getitem__(self, index):
    return self.features[index], self.labels[index]



In [12]:
dataset=CustomDataSet(x,y)
print(len(dataset))
print(dataset[2])


10
(tensor([-2.8954,  1.9769]), tensor(0))


In [13]:
dataloader=DataLoader(dataset,batch_size=2,shuffle=True)

In [14]:
for batch_features, batch_labels in dataloader:
  print(batch_features)
  print(batch_labels)

tensor([[-0.7206, -0.9606],
        [-1.1402, -0.8388]])
tensor([0, 0])
tensor([[ 1.0683, -0.9701],
        [-2.8954,  1.9769]])
tensor([1, 0])
tensor([[ 1.8997,  0.8344],
        [-0.9382, -0.5430]])
tensor([1, 1])
tensor([[-0.5872, -1.9717],
        [ 1.7273, -1.1858]])
tensor([0, 1])
tensor([[-1.9629, -0.9923],
        [ 1.7774,  1.5116]])
tensor([0, 1])


In [15]:
#Improve code and functionality
xtrain_tensor=[]
xtest_tensor=[]
ytrain_tensor=[]
ytest_tensor=[]


In [16]:
from torch.utils.data import Dataset, DataLoader

class CustomDataSet2(Dataset):
  def __init__(self,features,label):
    self.features=features
    self.label=label

  def __len__(self):
    return len(self.features)

  def __getitem__(self, index):
    return self.features[index], self.label[index]



In [17]:
train_dataset=CustomDataSet2(xtrain_tensor,ytrain_tensor)
test_dataset=CustomDataSet2(xtest_tensor,ytest_tensor)


In [18]:
train_loader=DataLoader(train_dataset,batch_size=32,shuffle=True)
test_loader=DataLoader(test_dataset,batch_size=32,shuffle=True)

ValueError: num_samples should be a positive integer value, but got num_samples=0

In [19]:
import torch.nn as nn
class MySimpleNN(nn.Module):
  def __init__(self,num_feature):
    super().__init__()
    self.linear=nn.Linear(num_feature,1)
    self.sigmoid=nn.Sigmoid()

  def forward(self,feature):
    out=self.linear(feature)
    out=self.sigmoid(out)
    return out

In [20]:
learning_rate=0.1
epochs=25

In [21]:
model=MySimpleNN(xtrain_tensor.shape[1])
optimizer=torch.optim.SGD(model.parameters(),lr=learning_rate)
loss_function=nn.BCELoss()

AttributeError: 'list' object has no attribute 'shape'

In [ ]:
for epoch in range(epochs):
  for batch_features, batch_labels in tran_loader:
    ypred=model(batch_features)
    loss=loss_function(ypred,batch_labels.view(-1,1))
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

In [ ]:
model.eval()
accuracy_list=[]

with torch.no_grad():
  for batch_features,batch_labels in test_loader:

    ypred=model(batch_features)
    ypred=(ypred>0.8).float()

    batch_accuracy=(ypred.view(-1)==batch_labels).float().mean().item()
    accuracy_list.append(batch_accuracy)

  overall_accuracy=sum(accuracy_list)/len(accuracy_list)
  print(f"Accuracy : {overall_accuracy}")