<a href="https://colab.research.google.com/github/Narware-Ayush/AI_ML/blob/main/tensor_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
print(torch.__version__)

2.11.0+cu128


In [ ]:
if torch.cuda.is_available():
  print("Gpu is available")
  print(f"using Gpu:{torch.cuda.get_device_name(0)}")
else:
  print("gpu is not available")

Gpu is available
using Gpu:Tesla T4


In [ ]:
a=torch.empty(2,3)
type(a)
print(a)
print(torch.zeros(2,4))
print(torch.ones(2,2,2))
print(torch.rand(2,3))
print(torch.manual_seed(100))
print(torch.rand(2,3))
print(torch.tensor([[1,2,3,4],[4,5,6,2]]))


# using empty

tensor([[1.8385e-05, 0.0000e+00, 0.0000e+00],
        [1.5046e-36, 1.5719e-09, 0.0000e+00]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])
tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])
tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])
tensor([[1, 2, 3, 4],
        [4, 5, 6, 2]])


In [ ]:
print(torch.arange(0,10,3))
print(torch.linspace(3,10,10))
print(torch.eye(3,3))
print(torch.full((3,3),5))

tensor([0, 3, 6, 9])
tensor([ 3.0000,  3.7778,  4.5556,  5.3333,  6.1111,  6.8889,  7.6667,  8.4444,
         9.2222, 10.0000])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


In [ ]:
x=torch.tensor([[1,2,3,4],[4,5,6,7]])
print(x.shape)
print(x.dtype)
y=torch.empty_like(x)
print(y)
print(torch,torch.zeros_like(x))
print(torch.tensor([[1,2.2323,3,4],[3,4,5,6]], dtype=torch.float32))

torch.Size([2, 4])
torch.int64
tensor([[8247607290818738232, 8241996831936114547, 3184106720196174452,
         7017841271895826976],
        [7143407337307529588, 8104636957451185263, 8243118355370701669,
         2480464647470542185]])
<module 'torch' from '/usr/local/lib/python3.12/dist-packages/torch/__init__.py'> tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]])
tensor([[1.0000, 2.2323, 3.0000, 4.0000],
        [3.0000, 4.0000, 5.0000, 6.0000]])


In [ ]:
#methemetical operations on tensors
x=torch.tensor([[2,4,6,6],[3,2,5,8],[9,6,4,11]])
y=torch.tensor([[2,3,4,4],[4,22,7,9],[8,5,2,1]])
print(x+y)
print(x*y)
print(x//2) #int division
print(x/2)

tensor([[ 4,  7, 10, 10],
        [ 7, 24, 12, 17],
        [17, 11,  6, 12]])
tensor([[ 4, 12, 24, 24],
        [12, 44, 35, 72],
        [72, 30,  8, 11]])
tensor([[1, 2, 3, 3],
        [1, 1, 2, 4],
        [4, 3, 2, 5]])
tensor([[1.0000, 2.0000, 3.0000, 3.0000],
        [1.5000, 1.0000, 2.5000, 4.0000],
        [4.5000, 3.0000, 2.0000, 5.5000]])
