<a href="https://colab.research.google.com/github/Narware-Ayush/AI_ML/blob/main/Torch_NN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as nn

class Model(nn.Module):
  def __init__(self,num_feature):
    super().__init__()
    self.linear=nn.Linear(num_feature,1)
    self.sigmoid=nn.Sigmoid()

  def forward(self,features):
    out=self.linear(features)
    out=self.sigmoid(out)
    return out

In [2]:
features=torch.rand(10,5)
model=Model(features.shape[1])
model(features)

tensor([[0.5276],
        [0.5444],
        [0.5527],
        [0.4807],
        [0.5500],
        [0.5349],
        [0.5419],
        [0.5250],
        [0.5390],
        [0.5488]], grad_fn=<SigmoidBackward0>)

In [3]:
print(model.linear.weight)
model.linear.bias

Parameter containing:
tensor([[-0.1584,  0.0741, -0.1532, -0.1437,  0.0804]], requires_grad=True)


Parameter containing:
tensor([0.2667], requires_grad=True)

In [4]:
!pip install torchinfo


In [5]:
from torchinfo import summary
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [6]:
#New neural network thoda complex
class Model1(nn.Module):
  def __init__(self,num_feature):
    super().__init__()
    self.linear1=nn.Linear(num_feature,3)
    self.relu=nn.ReLU()
    self.linear2=nn.Linear(3,1)
    self.sigmoid=nn.Sigmoid()

  def forward(self,features):
    out=self.linear1(features)
    out=self.relu(out)
    out=self.linear2(out)
    out=self.sigmoid(out)

    return out



In [7]:
features=torch.rand(10,5)
model=Model1(features.shape[1])
model(features)

tensor([[0.3385],
        [0.3833],
        [0.3316],
        [0.3482],
        [0.3429],
        [0.3443],
        [0.3580],
        [0.3183],
        [0.3338],
        [0.3239]], grad_fn=<SigmoidBackward0>)

In [8]:
model.linear1.weight
model.linear1.bias
model.linear2.weight
model.linear2.bias


Parameter containing:
tensor([-0.4577], requires_grad=True)

In [9]:
import torch.nn as nn

# containers
class Model2(nn.Module):
  def __init__(self,num_feature):
    super().__init__()
    self.network=nn.Sequential(
        nn.Linear(num_feature,3),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid(),
    )

  def forward(self,features):
    out=self.network(features)

    return out


In [12]:
features=torch.rand(10,5)
model=Model2(features.shape[1])
ypred=model(features)

In [14]:
loss_function=nn.BCELoss()
y_actual=torch.rand(10,1)
loss_function(ypred,y_actual)

tensor(0.7000, grad_fn=<BinaryCrossEntropyBackward0>)

In [16]:
# torch .optim use
optimizer=torch.optim.SGD(Model2.parameters(),lr=0.1)
optimizer.step()
optimizer.zero_grad()

TypeError: Module.parameters() missing 1 required positional argument: 'self'