<a href="https://colab.research.google.com/github/Narware-Ayush/AI_ML/blob/main/Training_pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [95]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder


In [96]:
df=pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
print(df.head())

         id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness

In [97]:
df.shape

(569, 33)

In [98]:
xtrain,xtest,ytrain,ytest=train_test_split(df.iloc[:,2:],df.iloc[:,1],test_size=0.2)
df.info()
#print(xtest.head())
print(ytrain.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5

In [99]:
scaler=StandardScaler()
xtrain=scaler.fit_transform(xtrain)
xtest=scaler.transform(xtest)
print(xtrain)

[[-0.91003692  0.49881094 -0.95029652 ... -0.7264371  -0.99841177
          nan]
 [-0.73090366 -1.07470796 -0.72418745 ...  0.04726758  0.3922173
          nan]
 [ 2.56742288  0.12198856  2.49869207 ... -0.00559423 -0.63033569
          nan]
 ...
 [-0.44656517 -0.55857549 -0.50963139 ... -1.59305041 -1.22301878
          nan]
 [-1.29559991 -1.56571894 -1.28739709 ... -0.73925208 -0.36381636
          nan]
 [-0.69109627  2.28243686 -0.68787796 ... -0.04403919 -0.66096391
          nan]]


/usr/local/lib/python3.12/dist-packages/sklearn/utils/extmath.py:1101: RuntimeWarning: invalid value encountered in divide
  updated_mean = (last_sum + new_sum) / updated_sample_count
/usr/local/lib/python3.12/dist-packages/sklearn/utils/extmath.py:1106: RuntimeWarning: invalid value encountered in divide
  T = new_sum / new_sample_count
/usr/local/lib/python3.12/dist-packages/sklearn/utils/extmath.py:1126: RuntimeWarning: invalid value encountered in divide
  new_unnormalized_variance -= correction**2 / new_sample_count


In [100]:
encoder=LabelEncoder()
ytrain=encoder.fit_transform(ytrain)
ytest=encoder.transform(ytest)
print(ytrain)
print(ytest)

[0 0 1 0 0 0 1 1 0 1 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 1 0 0 0 0 0 0 1 0
 1 0 1 0 1 0 1 0 0 0 1 1 0 0 1 0 0 0 1 0 0 1 0 1 0 1 0 0 1 1 0 0 0 0 1 0 0
 0 1 0 1 0 0 1 0 1 0 0 0 0 0 1 0 0 1 0 1 1 0 1 1 1 1 1 0 0 0 1 0 0 1 0 0 0
 1 1 0 0 0 1 1 0 1 0 1 0 0 0 0 1 0 0 0 1 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 1 0
 0 1 1 1 0 0 0 0 1 0 0 0 1 1 0 0 0 1 0 0 0 0 0 1 1 0 1 0 1 0 1 1 0 0 0 0 1
 0 1 1 1 1 1 1 1 1 0 1 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 0 0 0 0 0 1 0 0 0
 0 0 1 1 0 0 0 0 1 1 1 0 0 1 1 0 1 1 1 1 0 0 0 0 0 1 0 1 0 1 1 0 1 1 1 0 0
 0 1 0 0 1 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 0 0 1 0 0 1 0 1 0 0 0
 1 0 0 0 1 0 0 0 1 0 0 1 1 0 1 1 0 1 0 1 0 1 1 1 0 1 1 0 0 0 0 1 1 0 0 0 0
 0 0 0 1 1 1 0 1 0 1 0 0 1 1 1 1 1 1 0 1 1 0 0 0 0 0 1 1 0 0 1 0 1 1 0 0 1
 0 0 0 1 1 1 1 1 0 1 1 0 0 0 0 1 0 0 0 1 0 1 0 0 0 0 0 0 1 0 0 1 1 0 0 1 1
 0 1 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 1 1 0 0 0 1 1
 0 1 1 1 1 0 0 0 0 0 0]
[1 0 1 1 0 0 0 0 0 0 0 0 1 1 1 0 1 0 0 0 0 0 0 1 0 0 0 1 0 1 0 1 0 1 0 0 1
 

In [101]:
xtrain_tensor=torch.from_numpy(xtrain)
xtest_tensor=torch.from_numpy(xtest)
ytrain_tensor=torch.from_numpy(ytrain)
ytest_tensor=torch.from_numpy(ytest)

print(ytest_tensor)
print(xtrain_tensor)

tensor([1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1,
        0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1,
        0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0])
tensor([[-0.9100,  0.4988, -0.9503,  ..., -0.7264, -0.9984,     nan],
        [-0.7309, -1.0747, -0.7242,  ...,  0.0473,  0.3922,     nan],
        [ 2.5674,  0.1220,  2.4987,  ..., -0.0056, -0.6303,     nan],
        ...,
        [-0.4466, -0.5586, -0.5096,  ..., -1.5931, -1.2230,     nan],
        [-1.2956, -1.5657, -1.2874,  ..., -0.7393, -0.3638,     nan],
        [-0.6911,  2.2824, -0.6879,  ..., -0.0440, -0.6610,     nan]],
       dtype=torch.float64)


In [102]:
class mySimpleNeuNet():

  def __init__(self,x):
    self.weight=torch.rand(x.shape[1],1,requires_grad=True,dtype=torch.float64)
    self.bias=torch.zeros(1,dtype=torch.float64,requires_grad=True)

  def forward(self,x):
    z=torch.matmul(x,self.weight)+self.bias
    print(z)
    ypred=torch.sigmoid(z)
    return ypred

  def loss_function(self,ypred,y):
    epsilon=1e-7
    ypred=torch.clamp(ypred,epsilon,1-epsilon)

    loss=-(ytrain_tensor * torch.log(ypred) + (1-ytrain_tensor) * torch.log(1-ypred)).mean()
    return loss

In [103]:
learning_rate=0.1;
epochs=1;


In [104]:
#start training pipeline
#create model
model=mySimpleNeuNet(xtrain_tensor)
print(model.weight)
model.bias

tensor([[0.3419],
        [0.9325],
        [0.8989],
        [0.4106],
        [0.6744],
        [0.9331],
        [0.9288],
        [0.8633],
        [0.3346],
        [0.5014],
        [0.3523],
        [0.2688],
        [0.7860],
        [0.6729],
        [0.0664],
        [0.6904],
        [0.7827],
        [0.2267],
        [0.3784],
        [0.2629],
        [0.8857],
        [0.8602],
        [0.4950],
        [0.9619],
        [0.0523],
        [0.9316],
        [0.7604],
        [0.0951],
        [0.8036],
        [0.3263],
        [0.7772]], dtype=torch.float64, requires_grad=True)


tensor([0.], dtype=torch.float64, requires_grad=True)

In [109]:
#define loop
for epoch in range (epochs):
  ypred=model.forward(xtrain_tensor)
  loss=model.loss_function(ypred,ytrain_tensor)
  loss.backward()

  model.weight -= learning_rate * model.weight.grad

  model.bias.grad.zero_()
  model.weight.grad.zero_()

  print(f"print loass at each {epoch}")

tensor([[nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [n

RuntimeError: a leaf Variable that requires grad is being used in an in-place operation.

In [105]:
with torch.no_grad():
  ypred=model.forward(xtest_tensor)
  ypred=(ypred>0.5).float()
  print(ypred)